# Generated by Django 2.1.5 on 2019-09-12 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemSet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=10)),
                ('submissions', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('tags', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('constraints', models.TextField(default='')),
                ('inputDesc', models.TextField(default='')),
                ('outputDesc', models.TextField(default='')),
                ('problemSetter', models.CharField(default='', max_length=30)),
                ('problemTester', models.CharField(default='', max_length=30)),
                ('publishDate', models.DateField(default=datetime.date.today)),
                ('timeLimit', models.FloatField(default=0.0)),
            ],
        ),
    ]
