# Generated by Django 2.1.5 on 2019-09-10 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(blank=True, default='', max_length=50)),
                ('country', models.CharField(blank=True, default='', max_length=30)),
                ('rating', models.FloatField(default=0.0)),
                ('profilePicture', models.ImageField(blank=True, default='', upload_to='images/profilepic')),
                ('noOfSubmissions', models.IntegerField(default=0)),
                ('probSolved', models.CharField(blank=True, default='', max_length=20000)),
                ('probAttemped', models.CharField(blank=True, default='', max_length=20000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
